### ISSUE TITLE
mysql 계정 설정 / Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

### ISSUE THREAD

**Issue by suinautant** [suinautant/football_record#1]
[nodemon] restarting due to changes...
[nodemon] starting `node ./bin/www`
C:\WORKSPACE\DEVEL\PROJECT\football_record\routes\users.js:15
    if (err) throw err;
             ^

Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (C:\WORKSPACE\DEVEL\PROJECT\football_record\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\WORKSPACE\DEVEL\PROJECT\football_record\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\WORKSPACE\DEVEL\PROJECT\football_record\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\WORKSPACE\DEVEL\PROJECT\football_record\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\WORKSPACE\DEVEL\PROJECT\football_record\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\WORKSPACE\DEVEL\PROJECT\football_record\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\WORKSPACE\DEVEL\PROJECT\football_record\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\WORKSPACE\DEVEL\PROJECT\football_record\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Protocol._enqueue (C:\WORKSPACE\DEVEL\PROJECT\football_record\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\WORKSPACE\DEVEL\PROJECT\football_record\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at Connection.connect (C:\WORKSPACE\DEVEL\PROJECT\football_record\node_modules\mysql\lib\Connection.js:116:18)
    at Object.<anonymous> (C:\WORKSPACE\DEVEL\PROJECT\football_record\routes\users.js:12:12)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'ER_NOT_SUPPORTED_AUTH_MODE',
  errno: 1251,
  sqlMessage: 'Client does not support authentication protocol requested by server; consider upgrading MySQL client',
  sqlState: '08004',
  fatal: true
}

Node.js v17.2.0
[nodemon] app crashed - waiting for file changes before starting...

**Comment by suinautant** [comment]
-- RUN AND NOT FIX --
https://www.inflearn.com/questions/3637
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '사용할패스워드';

**Comment by suinautant** [comment]
-- RUN BUT NOT FIX --

https://www.inflearn.com/questions/3637
const mysql = require("mysql2");

mysql2 설치하고 수정 했으나 동일 현상이므로 mysql2 삭제

**Comment by suinautant** [comment]
mysql installer > server 옆에 reconfigure > Auth 설정가서 legacy 선택 > 완료 하면 잘 됩니다~
--
https://www.inflearn.com/questions/3637
